[package]
name = "wg"
version = "0.1.0"
authors = ["Justin Lovinger"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3", features = ["cargo"] }
html5ever = "0.25"
markup5ever_rcdom = "0.1"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
